// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  taskId: __t.u32().primaryKey().name("task_id"),
  taskKey: __t.string().name("task_key"),
  displayName: __t.string().name("display_name"),
  isActive: __t.bool().name("is_active"),
  requestHelp: __t.bool().name("request_help"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
